### ISSUE TITLE
Flood bugs due to mod

### ISSUE THREAD

**Issue by XionioXMaster** [team-abnormals/blueprint#132]
https://paste.loliidc.cn/?23421ff4ed432926#3Uj3HaaisXbT9dcLjmh7crad6XoJFknFjP1cwkGW5wRx

[31Oct2021 17:52:41.261] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@40b36b66 onChestGenerated(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		3: ASM: class net.mehvahdjukaar.supplementaries.setup.ModSetup onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class vectorwing.farmersdelight.setup.CommonEventHandler onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class com.minecolonies.coremod.event.EventHandler onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: class com.teammetallurgy.aquaculture.init.AquaLootTables onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: ASM: vazkii.quark.content.tools.EndermoshMusicDiscModule@387975f1 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		8: ASM: vazkii.quark.content.tools.module.AncientTomesModule@23b182aa onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		9: ASM: vazkii.quark.content.tools.module.ColorRunesModule@2d3fe179 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		10: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@2a84403c onChestGenerated(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		11: LOWEST
		12: ASM: class com.minecraftabnormals.abnormals_core.core.registry.LootInjectionRegistry onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		13: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@42294143 onLootTablesLoaded(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		14: ASM: com.integral.etherium.core.EtheriumEventHandler@24a98ec3 onLootTablesLoaded(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at com.minecraftabnormals.abnormals_core.common.loot.modification.LootModificationManager.onLootTableLoad(LootModificationManager.java:59)
	at net.minecraftforge.eventbus.ASMEventHandler_71_LootModificationManager_onLootTableLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:679)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:892)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:173)
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:51)
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:35)
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26)
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14)
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71)
	at mezz.jei.load.PluginLoader.lambda$new$3(PluginLoader.java:108)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:69)
	at mezz.jei.startup.ClientLifecycleHandler.startJEI(ClientLifecycleHandler.java:147)
	at mezz.jei.startup.ClientLifecycleHandler.setupJEI(ClientLifecycleHandler.java:140)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$3(ClientLifecycleHandler.java:106)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.lambda$handle$2(FMLPlayMessages.java:426)
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
	at net.minecraftforge.fml.network.FMLPlayMessages$SyncCustomTagTypes.handle(FMLPlayMessages.java:405)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91)
	at java.base/java.util.Optional.map(Optional.java:265)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.mIAvZQ7yUeNTJ0(Unknown Source)
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.main(Unknown Source)

**Comment by SmellyModder** [comment]
The commit above should fix these errors. _Abnormals Core_ assumed `LootTableLoadEvent` instances should only get fired after server reload listeners have been initialized, which should be the case.

The errors in the logs you have shown point to _Just Enough Resources_ firing `LootTableLoadEvent` instances at inappropriate times. _Abnormals Core_ wasn't prepared for such timing, and thus the `LootModificationManager` did not exist at the time of the events firing.

Ideally, _Just Enough Resources_ should be handling the registration of its loot tables after the server has loaded the loot tables. I would not be surprised if more minor issues exist in _Just Enough Resources_ because of this.
