### ISSUE TITLE
[1.18.2] Server conflict with Immersive Weathering

### ISSUE THREAD

**Issue by SH42913** [team-abnormals/blueprint#153]
When I try to run server where installed Blueprint and [Immersive Weathering](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge), server crashes(log is below). Log contains error from IW, but when I remove Blueprint everything works fine. Fun thing is client with both mods works fine. How can I solve it?

Error log:
```
[04Apr2022 10:20:01.815] [Worker-Main-4/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe immersive_weathering:prismarine_brick_wall
--
308 | com.google.gson.JsonSyntaxException: Unknown item 'minecraft:prismarine_brick_wall'
309 | at net.minecraftforge.common.crafting.CraftingHelper.getItem(CraftingHelper.java:155) ~[forge-1.18.2-40.0.36-universal.jar%23134!/:?]
310 | at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:181) ~[forge-1.18.2-40.0.36-universal.jar%23134!/:?]
311 | at net.minecraft.world.item.crafting.ShapedRecipe.m_151274_(ShapedRecipe.java:270) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
312 | at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:294) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
313 | at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:285) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
314 | at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.0.36-universal.jar%23134!/:?]
315 | at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:157) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
316 | at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
317 | at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
318 | at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
319 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
320 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
321 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
322 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
323 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
324 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
325 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
326 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
327 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
328 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
329 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
330 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
331 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
332 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
333 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
334 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
335 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
336 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
337 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
338 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
339 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
340 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
341 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
342 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
343 | at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_10855_(SimpleReloadInstance.java:51) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
344 | at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_6769_(SimpleReloadInstance.java:48) ~[server-1.18.2-20220228.144236-srg.jar%23130!/:?]
345 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
346 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
347 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
348 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
349 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
350 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
351 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
352 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
353 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by SmellyModder** [comment]
There's nothing in that log that points to the crash being caused by Blueprint. Please send the full crash report.

That error in the log you sent is entirely caused by Immersive Weathering.
`minecraft:prismarine_brick_wall` is not a Minecraft item so the `immersive_weathering:prismarine_brick_wall` recipe is failing to get deserialized.

**Comment by SH42913** [comment]
Tried again with Blueprint 5.3.1 version and everything works fine 👍
