### ISSUE TITLE
Crash: Non [a-z0-9_.-] character in namespace of location: all the creatures:texts/blueprint/splashes.json

### ISSUE THREAD

**Issue by FirDragon** [team-abnormals/blueprint#198]
https://github.com/team-abnormals/blueprint/blob/f091cf22c621c738cca98af557b50b8d938cfc5e/src/main/java/com/teamabnormals/blueprint/client/screen/splash/BlueprintSplashManager.java#L91C64-L91C68

I don't know why it's written that way, but it's clearly wrong.

**Comment by FirDragon** [comment]
Callstack:

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1934) ~[client-1.19.2-20220805.130853-srg.jar%23473!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:A,pl:runtimedistcleaner:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Minecraft-Mod-Language-Modpack-Converted-9.zip, Immersive Weathering Generated Pack, Global Resources, dynamic_asset_generator:assets, quark-emote-pack
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: all the creatures:texts/blueprint/splashes.json
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: all the creatures:texts/blueprint/splashes.json
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46)
	at TRANSFORMER/blueprint@6.1.2/com.teamabnormals.blueprint.client.screen.splash.BlueprintSplashManager.prepare(BlueprintSplashManager.java:91)
	at TRANSFORMER/blueprint@6.1.2/com.teamabnormals.blueprint.client.screen.splash.BlueprintSplashManager.m_5944_(BlueprintSplashManager.java:38)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

**Comment by FirDragon** [comment]
[crash-2023-06-27_12.57.18-client.txt](https://github.com/team-abnormals/blueprint/files/11877998/crash-2023-06-27_12.57.18-client.txt)

**Comment by FirDragon** [comment]
Sorry, I misread it, it's not your problem

**Comment by FirDragon** [comment]
Reason: https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/3418
