### ISSUE TITLE
Running into issue with blueprint mod

### ISSUE THREAD

**Issue by norfaremc** [team-abnormals/blueprint#199]
Server keeps soft crashing and then hard crashing. Insane lag. This was the log, any ideas?

---- Minecraft Crash Report ----
// Oops.

Time: 2023-07-02 17:51:27
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 600.00 seconds (should be max 0.05)
	at net.minecraft.world.level.levelgen.synth.ImprovedNoise.m_75327_(ImprovedNoise.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.PerlinNoise.m_75417_(PerlinNoise.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.PerlinNoise.m_75408_(PerlinNoise.java:150) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.NormalNoise.m_75380_(NormalNoise.java:98) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunction$NoiseHolder.m_224006_(DensityFunction.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$ShiftedNoise.m_207386_(DensityFunctions.java:669) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.m_207386_(DensityFunctions.java:385) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$Marker.m_207386_(DensityFunctions.java:456) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.m_207386_(DensityFunctions.java:385) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.biome.Climate$Sampler.m_183445_(Climate.java:453) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:classloading}
	at com.teamabnormals.blueprint.core.util.BiomeUtil$MultiNoiseModdedBiomeProvider.getNoiseBiome(BiomeUtil.java:168) ~[blueprint-1.19.2-6.1.2.jar%23363!/:6.1.2] {re:classloading}
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.m_203407_(ModdedBiomeSource.java:89) ~[blueprint-1.19.2-6.1.2.jar%23363!/:6.1.2] {re:mixin,re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_214004_(BiomeSource.java:94) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:citadel.mixins.json:BiomeSourceMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_215069_(ServerLevel.java:1126) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:flan.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.configuration.ModifyPlayerSpawnConfiguration.getSpawn(ModifyPlayerSpawnConfiguration.java:191) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.teleportToModifiedSpawn(ModifyPlayerSpawnPower.java:25) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.onRespawn(ModifyPlayerSpawnPower.java:49) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.onRespawn(ModifyPlayerSpawnPower.java:17) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.onRespawn(PowerFactory.java:192) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.onRespawn(ConfiguredPower.java:127) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.lambda$playerRespawn$8(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler$$Lambda$49006/0x000000080591f8a8.accept(Unknown Source) ~[?:?] {}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2372!/:?] {re:mixin}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.lambda$playerRespawn$9(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler$$Lambda$49005/0x000000080591f680.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.2.14-universal.jar%23584!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.playerRespawn(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.__ApoliEventHandler_playerRespawn_PlayerRespawnEvent.invoke(.dynamic) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$4423/0x0000000801b4e978.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerRespawnEvent(ForgeEventFactory.java:775) ~[forge-1.19.2-43.2.14-universal.jar%23584!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:472) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1603) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils$$Lambda$47395/0x00000008057836b8.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$43976/0x0000000805358f60.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.world.level.levelgen.synth.ImprovedNoise.m_75327_(ImprovedNoise.java:75) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.PerlinNoise.m_75417_(PerlinNoise.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.PerlinNoise.m_75408_(PerlinNoise.java:150) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.synth.NormalNoise.m_75380_(NormalNoise.java:98) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunction$NoiseHolder.m_224006_(DensityFunction.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$ShiftedNoise.m_207386_(DensityFunctions.java:669) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.m_207386_(DensityFunctions.java:385) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$Marker.m_207386_(DensityFunctions.java:456) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.m_207386_(DensityFunctions.java:385) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.world.level.biome.Climate$Sampler.m_183445_(Climate.java:453) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:classloading}
	at com.teamabnormals.blueprint.core.util.BiomeUtil$MultiNoiseModdedBiomeProvider.getNoiseBiome(BiomeUtil.java:168) ~[blueprint-1.19.2-6.1.2.jar%23363!/:6.1.2] {re:classloading}
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.m_203407_(ModdedBiomeSource.java:89) ~[blueprint-1.19.2-6.1.2.jar%23363!/:6.1.2] {re:mixin,re:classloading}
	at net.minecraft.world.level.biome.BiomeSource.m_214004_(BiomeSource.java:94) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender_forge.mixins.json:MixinBiomeSource,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:citadel.mixins.json:BiomeSourceMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_215069_(ServerLevel.java:1126) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:flan.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.configuration.ModifyPlayerSpawnConfiguration.getSpawn(ModifyPlayerSpawnConfiguration.java:191) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.teleportToModifiedSpawn(ModifyPlayerSpawnPower.java:25) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.onRespawn(ModifyPlayerSpawnPower.java:49) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.common.power.ModifyPlayerSpawnPower.onRespawn(ModifyPlayerSpawnPower.java:17) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading,pl:mixin:A}
	at io.github.edwinmindcraft.apoli.api.power.factory.PowerFactory.onRespawn(PowerFactory.java:192) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.api.power.configuration.ConfiguredPower.onRespawn(ConfiguredPower.java:127) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.lambda$playerRespawn$8(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler$$Lambda$49006/0x000000080591f8a8.accept(Unknown Source) ~[?:?] {}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2372!/:?] {re:mixin}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.lambda$playerRespawn$9(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler$$Lambda$49005/0x000000080591f680.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.2.14-universal.jar%23584!/:?] {re:mixin,re:classloading}
	at io.github.edwinmindcraft.apoli.common.ApoliEventHandler.playerRespawn(ApoliEventHandler.java:119) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading}
	at io.github.edwinmindcraft.apoli.common.__ApoliEventHandler_playerRespawn_PlayerRespawnEvent.invoke(.dynamic) ~[apoli-forge-1.19.2-2.6.1.0.jar%23619!/:1.19.2-2.6.1.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$4423/0x0000000801b4e978.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerRespawnEvent(ForgeEventFactory.java:775) ~[forge-1.19.2-43.2.14-universal.jar%23584!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:472) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1603) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils$$Lambda$47395/0x00000008057836b8.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23579!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}

**Comment by SmellyModder** [comment]
This doesn't look like a Blueprint issue. Blueprint will appear in the stack trace here because it alters some biome sources.

The top of the stack trace mentions a vanilla method.

Near the bottom of the stack trace, the Apoli mod's player respawning event listener is invoked. This leads to [this line of code](https://github.com/EdwinMindcraft/apoli/blob/1.19.x/forge/src/main/java/io/github/edwinmindcraft/apoli/common/power/configuration/ModifyPlayerSpawnConfiguration.java#L193) running. This line of code is expensive because the game has to potentially scan many, many block positions to find a valid biome. Depending on the player's spawn location, this line could definitely cause a ServerHangWatchdog detection.

I suggest removing that mod and seeing if the issue still occurs.

**Comment by SmellyModder** [comment]
Closing this due to inactivity and looks very unlikely to be caused by Blueprint.
