### ISSUE TITLE
last 1.20.1 update isnt working

### ISSUE THREAD

**Issue by iucamendonca** [team-abnormals/blueprint#222]
Time: 2024-03-07 00:44:02
Description: Exception in server tick loop

java.lang.ClassCastException: class com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager cannot be cast to class com.finndog.mns.mixins.resources.ReloadableResourceManagerImplAccessor (com.teamabnormals.blueprint.common.remolder.RemoldedResourceManager is in module blueprint@7.0.1 of loader 'TRANSFORMER' @29f8134; com.finndog.mns.mixins.resources.ReloadableResourceManagerImplAccessor is in module mns@1.0-1.20-forge of loader 'TRANSFORMER' @29f8134)
	at com.finndog.mns.utils.GeneralUtils.getAllFileStreams(GeneralUtils.java:244) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at com.finndog.mns.utils.GeneralUtils.getAllDatapacksJSONElement(GeneralUtils.java:281) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at com.finndog.mns.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:52) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at com.finndog.mns.MNSCommon.serverAboutToStart(MNSCommon.java:43) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at com.finndog.mns.events.base.EventHandler.invoke(EventHandler.java:25) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at com.finndog.mns.forge.MNSForge.onServerStarting(MNSForge.java:42) ~[mns-1.0-1.20-forge.jar%23437!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:98) ~[forge-1.20.1-47.2.20-universal.jar%23532!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithostitched.forge.mixins.json:common.ServerLifecycleHooksMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:162) ~[server-1.20.1-20230612.114412-srg.jar%23527!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23527!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:eeeabsmobs.mixins.json:ServerLoadMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23527!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:eeeabsmobs.mixins.json:ServerLoadMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}

**Comment by xd4rkzghost01** [comment]
Same here sadly, within Outer End (only mod i have that used Blueprint)

[BlueprintCrash](https://github.com/team-abnormals/blueprint/files/14518582/crash-2024-03-06_23.01.43-fml.txt)

Also ! i lost the latest log so i can only give the crash one.

**Comment by xd4rkzghost01** [comment]
I've tried the mod wihtout Outer End for my instance and still got a error

[Log without OuterEnd](https://github.com/team-abnormals/blueprint/files/14533009/2024-03-07-1.log)
[Force Crash](https://github.com/team-abnormals/blueprint/files/14533011/crash-2024-03-07_22.28.44-server.txt)

I've reported it at OuterEnd too and seem like an isssue from Blueprint .
