### ISSUE TITLE
1.20.1 crash: java.lang.IllegalStateException: Feature order cycle found

### ISSUE THREAD

**Issue by AlexModGuy** [team-abnormals/blueprint#232]
> java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:frozen_peaks]=net.minecraft.world.level.biome.Biome@3c5ded30}]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java:100) ~[client-1.20.1-20230612.114412-srg.jar%23340!/:?] {re:classloading}
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$3(ModdedBiomeSlicesManager.java:78) ~[blueprint-1.20.1-7.0.3.jar%23257!/:7.0.3] {re:mixin,re:classloading}

full crashlog:
https://gist.github.com/AlexModGuy/f40635f6ceb0879d503497b790ebbfd7

**Comment by bageldotjpg** [comment]
(very likely) not a blueprint issue despite it being mentioned in the stack trace, feature order cycle is technically a vanilla issue caused by adding features to biomes 'out of order'. Blueprint just gets mentioned because of the biome API.

[Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) should help you identify the actual mod responsible
