### ISSUE TITLE
Resource Loading

### ISSUE THREAD

**Issue by itsdeadfrosty** [team-abnormals/blueprint#261]
[latest.log](https://github.com/user-attachments/files/17606391/latest.log)

Error: IllegalArgumentException: null during palette loading for decorative pot textures.
Impact: Indicates missing or incompatible palette resources, potentially causing rendering issues.
Potential Conflict: Commonly paired with biomemakeover, clayworks, and alexscaves mods in error logs, suggesting resource conflicts.

**Comment by SmellyModder** [comment]
The actual cause of the crash is below. Also, if you read the crash more, you'll see many mods reporting errors with their paletted resources. This suggests the issue is something deeper.

```
[19:29:12] [Render thread/WARN]: Neruina caught an exception, see below for cause
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
	at dev.kosmx.playerAnim.api.layered.ModifierLayer.removeModifier(ModifierLayer.java:70) ~[player-animation-lib-forge-1.0.2-rc1+1.20.jar%231389!/:?]
	at net.minecraft.client.player.AbstractClientPlayer.playAnimation(AbstractClientPlayer.java:937) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.player.AbstractClientPlayer.playAnimation(AbstractClientPlayer.java:923) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:869) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.world.level.Level.mixinextras$bridge$accept$196(Level.java) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.2-forge+1.20.1.jar%231340!/:?]
	at net.minecraft.world.level.Level.wrapOperation$lcf000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:13540) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231586!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	```

**Comment by itsdeadfrosty** [comment]
its all hieroglyphics
